import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import Background from "../Component/Background";
import "./globals.css";

export const metadata: Metadata = {
  title: "Billionaire Bree | Luxury Hairstylist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Background />
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
